// Storage keys
export const SK_SESSION_CUSTOMER_ID = 'SESSION_CUSTOMER_ID';
export const SK_AUTHORIZE_ACCESS_CLIENT = 'AUTHORIZE_ACCESS_CLIENTE';
export const SK_USER_SESSION = 'USER_SESSION';
export const SK_SELECTED_COMPANY = 'SELECTED_COMPANY';
export const SK_REMEMBER_ME = 'REMEMBER_ME';
export const SK_USER_LOGIN = 'USER_LOGIN';

